### ISSUE TITLE
Allow all configuration items to be overridden

### ISSUE THREAD

**Issue by omallassi** [omallassi/adrust#16]
right now only some of the config items are configurable (conventions is apply for others). for instance you can only change "/tmp/adr-samples" and conventions will force "./templates" and "./src"

may be worth changing this. 

is related to #17

**Comment by pauda** [comment]
Note : on line 76 (and followings) of the code handling the configuration (adr_config_local_impl\src\config\mod.rs),  the template file name is hard coded and does not follow the configured one.
