### ISSUE TITLE
Add ID column to the `adr list` command

### ISSUE THREAD

**Issue by rustysys-dev** [omallassi/adrust#36]
In relation to #35 an `id` column should be added to the output as below.

```
 ID   |Title           | Date       | Status | File                                                   | Tags 
------+-----------------+------------+--------+--------------------------------------------------------+---------------------------------------
 1    | Loki Log Design | 2019-10-28 | wip    | /home/procyclinsur/adr/src/000001-loki-log-design.adoc | #Application_1 #Security #Deployment
```

where `ID` is equivalent to the number attached to the filename with insignificant 0's dropped.

**Comment by omallassi** [comment]
Honestly I like this one because once we have the ID we can use it in the CLi as you proposed in another one 
Which is better than the —path
