### ISSUE TITLE
Format Code

### ISSUE THREAD

**Issue by rustysys-dev** [omallassi/adrust#40]
During my last PR, I was unable to use a preferred editor due to it auto formatting the code base.  I would like to run the code though `cargo fmt` so that Atom which uses `cargo fmt` on save will no longer obscure the changes of a PR with extraneous formatting changes.

**Comment by omallassi** [comment]
@rustysys-dev - thx for this ! (and all PRs) 
I guess we can close this one (or do you want to force this in CI/CD?)

**Comment by rustysys-dev** [comment]
It would be great for the CICD to force!

Ill close this one out!
