### ISSUE TITLE
Proposal: rename `--name` to `--title`

### ISSUE THREAD

**Issue by omallassi** [omallassi/adrust#45]
this is not "revolution of the year", yet, Instead of running 
````
adr new lf --name "my decision title"
````

we could run 
````
adr new lf --title "my decision title"
````

**Comment by omallassi** [comment]
@rustysys-dev : thoughts?

**Comment by rustysys-dev** [comment]
I think either one is easy to use!  

If you prefer `--title` I think its a good switch, definately more representative of the function i.e. the title is set to the input value, where as the filename may have an ID attached.
